name = "Mycelia"
author = "Furglitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b0a9c3e5c3bb5079d6fe31d93204a5ce4b1d4c91ac98306c5a9d790ab274955"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
