name = "Mycelia"
author = "Furglitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b5af0e44fe5ea42e4cdc59108891a0cd3b4f1ddf89ef88e3ca80eabf5a7521a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
