name = "Mycelia"
author = "Furglitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d621fdb5fda193fa1dd75baed2b4db785fbbc825b4858ed378e997e3222f4a0d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
